### ISSUE TITLE
前端文档补充计划

### ISSUE THREAD

**Issue by danranVm** [cntehang/public-dev-docs#17]
# 前端文档补充计划

## ng-common-lib 公共库的管理
- 版本管理计划
- 公共库代码提交规范

## 业务组件
- [ ] 业务组件说明文档

## Angular 相关最佳实践
- 应用启动过程
- service
- http api
- pipe
- directive
- form 
  - form 组件的二次封装
  - 表单交互（输入输出以及修改值、错误提示、表单的动态渲染（新增，删除），动态表单组件）

## 菜单权限管理设计与规范

**Comment by c1xf** [comment]
路由配置、菜单权限

**Comment by c1xf** [comment]
项目启动过程？

**Comment by YingLiu4203** [comment]
进行的怎么样了，可以开些小issue，不断close

**Comment by danranVm** [comment]
@chendye 菜单权限管理设计与规范
@Mspedestrian 基础数据的获取与缓存管理
@loveholly 路由的设计与规范
@danranVm ng-common-lib 公共库的管理 以及 Angular 相关最佳实践，启动过程，service，http, form 等文档
